### PR TITLE
Editor-Add Lines Numbers

### PR DESCRIPTION
**Pull request by impAkshat**
Issue: #154 

- Added Lines Number in Editor
- Added event listener so that when the value of editor-codebox changes
- Overflow in the Lines Number handled, scrolling of line number based on scrolling of textarea

### CODE REVIEW

**Review by meganindya — COMMENTED** [review]
Screenshot 2022-02-11 at 11 36 22 PM

Functionally looks fine but UI is messed up. I'll fix the styling.

**Comment by meganindya** [comment]
I'll add this feature in a patch release later. Too many variables.

**Comment by surajkumar-sk** [comment]
Hey , 
@impAkshat  I think @meganindya is busy with a lot of work. I read your code and I think I can fix all the issues with UI, would you be fine with me collaborating on this PR?

**Comment by impAkshat** [comment]
@surajkumar-sk this issue is actually a part of a project in GSOC 22. So, leave it for now or apply for the gsoc project and work on this issue there.

**Comment by impAkshat** [comment]
@surajkumar-sk this issue is actually a part of a project in GSOC 22. So, leave it for now or apply for the gsoc project, and work on it there.

**Comment by surajkumar-sk** [comment]
@impAkshat could you be more specific on which project this PR is linked to. In the projects list there's only one project about code editor and that doesn't include adding a number line.

**Comment by meganindya** [comment]
There's a prospective project for a powerful text editor. The current one is only a makeshift prototype and adding cosmetic features to it will be redundant.

**Pull request closed without merging**
