### PR TITLE
feat(code-builder): implement final classes and components for the 4 brick types

### LINKED ISSUE #329: Implement final classes for the 4 brick types: Data, Expression, Statement, and Block and create React components for bricks
## Objectives

- Implement the final classes as described in #328.
- Replace `SVG` getter with `get paths(): string[]` getter
- For design 0, implement `paths` getters for each such final classes that return the corresponding SVG path strings based off of the intrinsic and current ephemeral state properties of the corresponding brick instances, using the `generatePath` utility `path.ts` utility
- Create React components for all 4 brick types in `design0/components`
  - Instantiate final class based on the type with appropriate arguments
  - Return an SVG group tag (`<g>...</g>`) that encapsulates the path and the labels
  - Add styling properties to the appropriate tags
- Use those newly created components for Storybook stories

### PR DESCRIPTION
**Pull request by niloysikdar**
### This Pull Request covers the following:

- Implement the final classes as described in #328
- Implement the `SVGpaths` getter which returns `string[]`
- Generate the path for the SVGs for different types of Bricks using the `generatePath` utility method
- Create 4 different React components for the bricks under `design0/components`
    - `modules/code-builder/src/brick/design0/components/BrickBlock.tsx`
    - `modules/code-builder/src/brick/design0/components/BrickData.tsx`
    - `modules/code-builder/src/brick/design0/components/BrickExpression.tsx`
    - `modules/code-builder/src/brick/design0/components/BrickStatement.tsx`
- Add styling properties to the appropriate tags
- Fix Storybook stories for the components under `modules/code-builder/src/brick/stories`

### Here are some of the Storybook screenshots:

The `generatePath` utility function has some bugs which are also reported here #339 

Closes #329

### CODE REVIEW

**Review by meganindya — APPROVED** [review]

**Comment by meganindya** [comment]
Time for #341 I guess. Add to this branch itself.

**Comment by meganindya** [comment]
I added a couple more commits on top

**Comment by niloysikdar** [comment]
> I added a couple more commits on top

Thanks @meganindya, working on #341 as per your suggestion.

**Comment by meganindya** [comment]
Merging this branch for now. Let's account for the further in week 6.

**Pull request merged**
