### PR TITLE
component - singer: add synthUtils

### PR DESCRIPTION
**Pull request by walterbender**
Utilities for managing interface to synth.

    /**
     * Returns a Tone.js synth for an instrument
     * @throws {InvalidArgumentError}
     */
    getBuiltinSynth: (instrumentName: string, instance?: number) => Tone.PolySynth | undefined;

    /**
     * Returns a Tone.js synth for an instrument
     * @throws {InvalidArgumentError}
     */
    getSampler: (instrumentName: string, instance?: number) => Tone.Sampler | undefined;

    /**
     * Returns a Tone.js synth for an instrument
     * @throws {InvalidArgumentError}
     */
    getPlayer: (instrumentName: string, instance?: number) => Tone.Player | undefined;

    /**
     * Adds a new voice instance with that voice's synths and status
     */
    addVoice: (instance: number) => void;

    /**
     * Returns note value in seconds
     */
    noteValueToSeconds: (noteValue: number, instance?: number) => number;

    /**
     * Plays a note.
     * @throws {InvalidArgumentError}
     */
    trigger: (pitches: (string|number)[], noteValue: number, instrumentName: string, instance: number) => void;

### CODE REVIEW

**Review by meganindya — COMMENTED** [review]
I'd want to separate the `package.json` changes in a separate PR, and bundle up the linting with the `feat` commits. Basically, my idea is that if every commit should pass lint test.

I can do that rearranging though. Can you tell me how you'd want to test these? So I'll create a basic test bench, after which you can rebase and test this branch.

**Comment by walterbender** [comment]
Probably best to make a fresh PR.
re tests, I will add some for each method once I have a framework in which to do so...

**Comment by meganindya** [comment]
So you want to call the methods individually in the test?

**Comment by walterbender** [comment]
I want to do the equivalent of unit test coverage, but I cannot due to the audio context issue. Making sure the synth is generating the anticipated sounds would be good too.

**Comment by meganindya** [comment]
I think cypress should get that part done. It's already configured. I'll explore and add a guide to use that.

**Pull request closed without merging**
