### PR TITLE
added dropdown

### PR DESCRIPTION
**Pull request by Tushar98644**
part of #272

### CODE REVIEW

**Comment by Tushar98644** [comment]
@meganindya  kindly review

**Comment by meganindya** [comment]
I don't think you read the issue description and the code quality guidelines :p.

I'm gonna keep this on hold while I make the mockup for this component. I'd advise you to follow the guidelines. I'm trying to keep the codebase consistent, so I'm strict about what goes into the repository.

Meanwhile, you can try the other unblocked ones, e.g. WButtonIcon, WButtonText

**Comment by Tushar98644** [comment]
> I don't think you read the issue description and the code quality guidelines :p.
> 
> I'm gonna keep this on hold while I make the mockup for this component. I'd advise you to follow the guidelines. I'm trying to keep the codebase consistent, so I'm strict about what goes into the repository.
> 
> Meanwhile, you can try the other unblocked ones, e.g. WButtonIcon, WButtonText

ok sir ,i am extremely sorry for the inconvenience ...i will work on the unlocked ones and try to keep the code quality consistent ...

**Comment by meganindya** [comment]
There is a Figma mockup file linked in the description.

**Comment by Tushar98644** [comment]
> There is a Figma mockup file linked in the description.

yes sir, i am developing the components according to that ....could you tell me what the handleclick event is supposed to do in the WTextButton ?

**Comment by meganindya** [comment]
it's a callback for when the button is clicked.

And I'm not a sir 🙂

**Pull request closed without merging**
