### PR TITLE
feat(common):[components] add WToggleSwitchRounded

### LINKED ISSUE #295: Enhancement of Toggle switch UI
While viewing the components in storybook i found that the toggle switch has a rather outdated uI:

Screenshot 2023-01-21 at 9 39 58 PM

It can be enhanced to look something like this:

Screenshot 2023-01-21 at 9 42 50 PM
Screenshot 2023-01-21 at 9 43 09 PM

### PR DESCRIPTION
**Pull request by Tushar98644**
Part of #272
fixes #295 
 
Screenshot 2023-01-22 at 4 17 32 PM

Screenshot 2023-01-22 at 4 17 57 PM

### CODE REVIEW

**Comment by Tushar98644** [comment]
The previous pr kind of got messy so created a new one @meganindya

**Comment by meganindya** [comment]
seems like your local git config email isn't synchronised with your github account

run in terminal
```shell
git config --global user.name "<YOUR NAME>"
git config --global user.email <YOUR EMAIL>
```

**Comment by Tushar98644** [comment]
> seems like your local git config email isn't synchronised with your github account
> 
> run in terminal
> 
> ```shell
> git config --global user.name "<YOUR NAME>"
> git config --global user.email <YOUR EMAIL>
> ```

done...... also i had one question, can we create issues for adding new react components ?

**Comment by meganindya** [comment]
We're discussing the expected UI. Currently, I made a quick draft UI just to get started. No point in creating components that may not be utilised.

**Comment by Tushar98644** [comment]
> We're discussing the expected UI. Currently, I made a quick draft UI just to get started. No point in creating components that may not be utilised.

okay...will start working on wcheckbox and wIconbutton now...

**Comment by Tushar98644** [comment]
@meganindya what should the callbackfunction on buttonclick  be set to? set it to some undefined function or link to the same element?

**Comment by meganindya** [comment]
not sure I understand

**Comment by Tushar98644** [comment]
> not sure I understand

I mean the handleclicker of WIconbutton

**Comment by meganindya** [comment]
`handlerClick` will be a callback function passed as a prop. This is exactly like `WTextButton`.

**Pull request merged**
